// <auto-generated />
using System.Collections.Generic;
using HearthStone_Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HearthStone_Backend.Migrations
{
    [DbContext(typeof(CardDBContext))]
    [Migration("20201020143303_tables")]
    partial class tables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HearthStone_Backend.Models.Card", b =>
                {
                    b.Property<string>("CardId")
                        .HasColumnType("text");

                    b.Property<string>("Artist")
                        .HasColumnType("text");

                    b.Property<string>("Attack")
                        .HasColumnType("text");

                    b.Property<string>("CardSet")
                        .HasColumnType("text");

                    b.Property<bool>("Collectable")
                        .HasColumnType("boolean");

                    b.Property<string>("Cost")
                        .HasColumnType("text");

                    b.Property<bool>("Elite")
                        .HasColumnType("boolean");

                    b.Property<string>("Faction")
                        .HasColumnType("text");

                    b.Property<string>("Flavor")
                        .HasColumnType("text");

                    b.Property<string>("Health")
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Race")
                        .HasColumnType("text");

                    b.Property<string>("Rarity")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("img")
                        .HasColumnType("text");

                    b.Property<string>("imgGold")
                        .HasColumnType("text");

                    b.HasKey("CardId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("HearthStone_Backend.Models.CardBack", b =>
                {
                    b.Property<string>("CardBackId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Img")
                        .HasColumnType("text");

                    b.Property<string>("ImgAnimated")
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("SortCategory")
                        .HasColumnType("text");

                    b.Property<string>("SortOrder")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.HasKey("CardBackId");

                    b.ToTable("CardBacks");
                });

            modelBuilder.Entity("HearthStone_Backend.Models.Info", b =>
                {
                    b.Property<List<string>>("Classes")
                        .HasColumnType("text[]");

                    b.Property<List<string>>("Factions")
                        .HasColumnType("text[]");

                    b.Property<List<string>>("Locales")
                        .HasColumnType("text[]");

                    b.Property<List<string>>("Qualities")
                        .HasColumnType("text[]");

                    b.Property<List<string>>("Races")
                        .HasColumnType("text[]");

                    b.Property<List<string>>("Sets")
                        .HasColumnType("text[]");

                    b.Property<List<string>>("Standard")
                        .HasColumnType("text[]");

                    b.Property<List<string>>("Types")
                        .HasColumnType("text[]");

                    b.Property<List<string>>("Wild")
                        .HasColumnType("text[]");

                    b.ToTable("Info");
                });
#pragma warning restore 612, 618
        }
    }
}
